### PR TITLE
Update CorsAllowAnyOriginAttribute.cs

### PR DESCRIPTION
**Pull request by parsley72**
#83 Add custom headers for CORS.

### CODE REVIEW

**Comment by parsley72** [comment]
I couldn't test this because there are no instructions in the README, but it builds fine.

**Comment by mderriey** [comment]
Hey, thanks for opening a PR!

However, if you want allowed headers to be returned in the `Access-Control-Allow-Headers` header, you can specify them in your request in the `Access-Control-Request-Headers` header.

See just below of your change:

https://github.com/Readify/httpstatus/blob/c96be24629dd3f16b7af6d3ccbe9b45a730270a7/src/Teapot.Web/CorsAllowAnyOriginAttribute.cs#L14-L20

Would that work for you?

**Comment by parsley72** [comment]
No. Read my comment on the issue: https://github.com/Readify/httpstatus/issues/83#issuecomment-684168796

**Comment by parsley72** [comment]
Are you waiting for something from me?

**Pull request merged**
