### PR TITLE
Check if AcceptTypes array is present before checking contents

### PR DESCRIPTION
**Pull request by mattbaker**
Addresses #37

### CODE REVIEW

**Comment by mattbaker** [comment]
Tested locally and this does the trick.

**Comment by aaronpowell** [comment]
Curious to your use case where you're not sending `Accept` headers

**Comment by mattbaker** [comment]
Sure! In our case we needed a response with a specific status code, but had no use for the response body. Since the format of the response body was irrelevant we didn't include an Accept header.

Thanks for the merge :)

**Comment by aaronpowell** [comment]
Cool, thanks for the insight. I've only ever used it from the browser so I always send `Accept` headers 😛

**Pull request merged**
