### PR TITLE
Update StatusCodeResults.cs

### PR DESCRIPTION
**Pull request by alecrabbit**
520
522
524

### CODE REVIEW

**Comment by aaronpowell** [comment]
Are these standard codes? I'm not familiar with them

**Comment by alecrabbit** [comment]
cloudflare uses them

2015-04-04 4:04 GMT+03:00 Aaron Powell <notifications@github.com>:

**Comment by aaronpowell** [comment]
Cool, merged and should be live shortly

**Comment by aaronpowell** [comment]
Wait, no, I cant merge off my phone 😒. Might have to wait until after the long weekend when in back on my laptop

**Comment by tathamoddie** [comment]
Deployed.

**Pull request merged**
